/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package main */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "collected_entity.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "collection_filter.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "collector.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "entity_statement.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "federation_entity_metadata.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "federation_leaf.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "jws_headers.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "map.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "metadata.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "openid_provider_metadata.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "openid_relying_party_metadata.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "request_producer.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "signature_algorithm.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "signer.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "single_key_storage.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "trust_anchor.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 12 "trust_mark.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "trust_resolver.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "ui_info.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void oidfedCollectedEntityDestroy(struct oidfed_collected_entity* ce);
extern struct oidfed_collected_entity_ui_enumerator oidfedCollectedEntityEnumerateUi(struct oidfed_collected_entity ce);
extern _Bool oidfedCollectedEntityNextUi(struct oidfed_collected_entity_ui_enumerator* enumer);
extern void oidfedCollectedEntityFinishUi(struct oidfed_collected_entity_ui_enumerator* enumer);
extern struct oidfed_ui_info oidfedCollectedEntityGetUiValue(struct oidfed_collected_entity_ui_enumerator* enumer);
extern struct oidfed_collection_filter oidfedEmptyCollectionFilter(void);
extern void oidfedCollectionFilterDestroy(struct oidfed_collection_filter* cfs);
extern void oidfedCollectionFilterAppend(struct oidfed_collection_filter* cfs, uintptr_t filter);
extern uintptr_t oidfedEntityCollectionFilterOPSupportsExplicitRegistration(char** taIds, size_t taIdsCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportsAutomaticRegistration(char** taIds, size_t taIdsCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes(char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportedScopesIncludes(char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount);
extern uintptr_t oidfedEntityCollectionFilterOPs(void);
extern void oidfedCollectorDestroy(struct oidfed_collector* collector);
extern struct oidfed_collector oidfedCollectorCreateSimple(void);
extern struct oidfed_collector oidfedCollectorCreateSmart(struct oidfed_trust_anchor* anchors, size_t anchorsCount);
extern int oidfedCollectorCollectVerifiedEntities(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount);
extern int oidfedCollectorCollectVerifiedEntitiesWithFilter(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount);
extern struct oidfed_entity_statement oidfedEntityStatementParse(char* jwt, size_t jwtLen, int* errc);
extern void oidfedEntityStatementDestroy(struct oidfed_entity_statement* stmt);
extern struct oidfed_entity_statement oidfedGetEntityConfiguration(char* entityID, int* errc);
extern struct oidfed_federation_entity_metadata oidfedFederationEntityMetadataCreate(void);
extern char* oidfedFederationEntityMetadataGetFederationFetchEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationFetchEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationListEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationListEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationResolveEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationResolveEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint(struct oidfed_federation_entity_metadata m, char* endpoint);
extern char* oidfedFederationEntityMetadataGetLogoURI(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetLogoURI(struct oidfed_federation_entity_metadata m, char* logoURI);
extern char* oidfedFederationEntityMetadataGetPolicyURI(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetPolicyURI(struct oidfed_federation_entity_metadata m, char* policyURI);
extern char* oidfedFederationEntityMetadataGetInformationURI(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetInformationURI(struct oidfed_federation_entity_metadata m, char* informationURI);
extern char* oidfedFederationEntityMetadataGetOrganizationName(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetOrganizationName(struct oidfed_federation_entity_metadata m, char* organizationName);
extern char* oidfedFederationEntityMetadataGetOrganizationURL(struct oidfed_federation_entity_metadata m);
extern void oidfedFederationEntityMetadataSetOrganizationURL(struct oidfed_federation_entity_metadata m, char* organizationURL);
extern void oidfedFederationEntityMetadataDestroy(struct oidfed_federation_entity_metadata* m);
extern struct oidfed_federation_leaf oidfedFederationLeafCreate(char* entityID, char** authorityHints, size_t authorityHintsCount, char** trustAnchorHints, size_t trustAnchorHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc);
extern void oidfedFederationLeafDestroy(struct oidfed_federation_leaf* leaf);
extern int oidfedFederationLeafGetAsJWT(struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount);
extern struct oidfed_request_producer oidfedFederationLeafGetRequestObjectProducer(struct oidfed_federation_leaf leaf);
extern struct oidfed_jws_headers oidfedJWSHeadersCreate(void);
extern void oidfedJWSHeadersDestroy(struct oidfed_jws_headers* h);
extern int oidfedJWSHeadersSet(struct oidfed_jws_headers h, char* key, char* value);
extern struct oidfed_map oidfCreateMap(void);
extern _Bool oidfMapHasKey(struct oidfed_map m, char* key);
extern void oidfMapSetString(struct oidfed_map m, char* key, char* value);
extern void oidfMapSetInt64(struct oidfed_map m, char* key, int64_t value);
extern void oidfMapDestroy(struct oidfed_map* m);
extern struct oidfed_metadata oidfedMetadataCreate(void);
extern struct oidfed_openid_provider_metadata oidfedMetadataGetOPMetadata(struct oidfed_metadata m);
extern void oidfedMetadataSetOPMetadata(struct oidfed_metadata m, struct oidfed_openid_provider_metadata op);
extern uintptr_t oidfedMetadataGetRPMetadata(struct oidfed_metadata m);
extern void oidfedMetadataSetRPMetadata(struct oidfed_metadata m, uintptr_t rp);
extern uintptr_t oidfedMetadataGetFederationEntityMetadata(struct oidfed_metadata m);
extern void oidfedMetadataSetFederationEntityMetadata(struct oidfed_metadata m, uintptr_t fe);
extern char* oidfedOpenIDProviderMetadataGetAuthorizationEndpoint(struct oidfed_openid_provider_metadata m);
extern char* oidfedOpenIDProviderMetadataGetTokenEndpoint(struct oidfed_openid_provider_metadata m);
extern char* oidfedOpenIDProviderMetadataGetIssuer(struct oidfed_openid_provider_metadata m);
extern void oidfedOpenIDProviderMetadataDestroy(struct oidfed_openid_provider_metadata* m);
extern struct oidfed_openid_relying_party_metadata oidfedOpenIDRelyingPartyMetadataCreate(void);
extern char* oidfedOpenIDRelyingPartyMetadataGetClientID(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetClientID(struct oidfed_openid_relying_party_metadata rp, char* clientID);
extern char* oidfedOpenIDRelyingPartyMetadataGetClientName(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetClientName(struct oidfed_openid_relying_party_metadata rp, char* clientName);
extern void oidfedOpenIDRelyingPartyMetadataSetRedirectUris(struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count);
extern void oidfedOpenIDRelyingPartyMetadataSetResponseTypes(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
extern void oidfedOpenIDRelyingPartyMetadataSetGrantTypes(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
extern char* oidfedOpenIDRelyingPartyMetadataGetApplicationType(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetApplicationType(struct oidfed_openid_relying_party_metadata rp, char* applicationType);
extern char* oidfedOpenIDRelyingPartyMetadataGetLogoURI(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetLogoURI(struct oidfed_openid_relying_party_metadata rp, char* logoURI);
extern uintptr_t oidfedOpenIDRelyingPartyMetadataGetJWKS(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetJWKS(struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks);
extern void oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage(struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage);
extern char* oidfedOpenIDRelyingPartyMetadataGetOrganizationName(struct oidfed_openid_relying_party_metadata rp);
extern void oidfedOpenIDRelyingPartyMetadataSetOrganizationName(struct oidfed_openid_relying_party_metadata rp, char* organizationName);
extern void oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
extern void oidfedOpenIDRelyingPartyMetadataDestroy(struct oidfed_openid_relying_party_metadata* rp);
extern struct oidfed_request_producer oidfedRequestProducerCreate(char* entityId, int64_t duration, struct oidfed_versatile_signer signer);
extern void oidfedRequestProducerDestroy(struct oidfed_request_producer* producer);
extern struct oidfed_signed_bytes oidfedRequestProducerProduceObject(struct oidfed_request_producer producer, struct oidfed_map requestValues, struct oidfed_jws_headers headers, char** algorithms, size_t algorithmsCount, int* errc);
extern struct oidfed_signed_bytes oidfedRequestProducerClientAssertion(struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc);
extern char* oidfedRequestProducerExchangeCode(struct oidfed_request_producer producer, char* tokenEndpoint, char* code, char* redirectURI, int* errc);
extern char* oidfedExtractSubjectFromTokenResponse(char* tokenResponse);
extern void oidfedSignedBytesDestroy(struct oidfed_signed_bytes* sb);
extern char* oidfedSignedBytesGetData(struct oidfed_signed_bytes sb, size_t* count);
extern struct oidfed_signature_algorithm oidfedSignatureAlgorithmCreateEmpty(void);
extern void oidfedSignatureAlgorithmDestroy(struct oidfed_signature_algorithm* sa);
extern struct oidfed_signature_algorithm oidfedSignatureAlgorithmGet(char* name, _Bool* succ);
extern struct oidfed_signer oidfedSignerCreateFromPEM(char* pemBytes, size_t pemCount, int* errc);
extern void oidfedSignerDestroy(struct oidfed_signer* s);
extern struct oidfed_single_key_storage oidfedSingleKeyStorageCreate(struct oidfed_signer signer, struct oidfed_signature_algorithm alg);
extern void oidfedSingleKeyStorageDestroy(struct oidfed_single_key_storage* sks);
extern void oidfedTrustAnchorDestroy(struct oidfed_trust_anchor* ta);
extern struct oidfed_trust_anchor oidfedTrustAnchorCreate(char* id);
extern struct oidfed_trust_mark oidfedTrustMarkCreate(void);
extern void oidfedTrustMarkSetType(struct oidfed_trust_mark tm, char* typ);
extern char* oidfedTrustMarkGetType(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetIssuer(struct oidfed_trust_mark tm, char* issuer);
extern char* oidfedTrustMarkGetIssuer(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetJwt(struct oidfed_trust_mark tm, char* jwt);
extern char* oidfedTrustMarkGetJwt(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetRefresh(struct oidfed_trust_mark tm, _Bool refresh);
extern _Bool oidfedTrustMarkIsRefresh(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetMinLifetimeSeconds(struct oidfed_trust_mark tm, uint64_t minLifetime);
extern uint64_t oidfedTrustMarkGetMinLifetimeSeconds(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetRefreshGracePeriod(struct oidfed_trust_mark tm, uint64_t refreshGracePeriod);
extern uint64_t oidfedTrustMarkGetRefreshGracePeriod(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkDestroy(struct oidfed_trust_mark* tm);
extern struct oidfed_trust_resolver oidfedTrustResolverCreate(char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount);
extern void oidfedTrustResolverDestroy(struct oidfed_trust_resolver* r);
extern struct oidfed_trust_chains oidfedTrustResolverResolveToValidChains(struct oidfed_trust_resolver r);
extern size_t oidfedTrustChainsCount(struct oidfed_trust_chains chains);
extern struct oidfed_trust_chain oidfedTrustChainsGet(struct oidfed_trust_chains chains, size_t index);
extern void oidfedTrustChainsDestroy(struct oidfed_trust_chains* chains);
extern void oidfedTrustChainDestroy(struct oidfed_trust_chain* chain);
extern struct oidfed_metadata oidfedTrustChainGetMetadata(struct oidfed_trust_chain chain, int* errc);
extern void oidfedMetadataDestroy(struct oidfed_metadata* m);
extern void oidfedUiInfoDestroy(struct oidfed_ui_info* ui);

#ifdef __cplusplus
}
#endif
