/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "collected_entity.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "collection_filter.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "collector.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "entity_statement.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "federation_leaf.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "map.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "metadata.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "request_producer.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "signature_algorithm.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "signer.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "single_key_storage.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "trust_anchor.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 11 "trust_mark.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "trust_resolver.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"

#line 3 "ui_info.go"

#include "oidfed_wrap.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void oidfedCollectedEntityDestroy(struct oidfed_collected_entity* ce);
extern struct oidfed_collected_entity_ui_enumerator oidfedCollectedEntityEnumerateUi(struct oidfed_collected_entity ce);
extern _Bool oidfedCollectedEntityNextUi(struct oidfed_collected_entity_ui_enumerator* enumer);
extern void oidfedCollectedEntityFinishUi(struct oidfed_collected_entity_ui_enumerator* enumer);
extern struct oidfed_ui_info oidfedCollectedEntityGetUiValue(struct oidfed_collected_entity_ui_enumerator* enumer);
extern struct oidfed_collection_filter oidfedEmptyCollectionFilter(void);
extern void oidfedCollectionFilterDestroy(struct oidfed_collection_filter* cfs);
extern void oidfedCollectionFilterAppend(struct oidfed_collection_filter* cfs, uintptr_t filter);
extern uintptr_t oidfedEntityCollectionFilterOPSupportsExplicitRegistration(char** taIds, size_t taIdsCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportsAutomaticRegistration(char** taIds, size_t taIdsCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes(char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount);
extern uintptr_t oidfedEntityCollectionFilterOPSupportedScopesIncludes(char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount);
extern uintptr_t oidfedEntityCollectionFilterOPs(void);
extern void oidfedCollectorDestroy(struct oidfed_collector* collector);
extern struct oidfed_collector oidfedCollectorCreateSimple(void);
extern struct oidfed_collector oidfedCollectorCreateSmart(struct oidfed_trust_anchor* anchors, size_t anchorsCount);
extern int oidfedCollectorCollectVerifiedEntities(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount);
extern int oidfedCollectorCollectVerifiedEntitiesWithFilter(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount);
extern struct oidfed_entity_statement oidfedEntityStatementParse(char* jwt, size_t jwtLen, int* errc);
extern void oidfedEntityStatementDestroy(struct oidfed_entity_statement* stmt);
extern struct oidfed_entity_statement oidfedGetEntityConfiguration(char* entityID, int* errc);
extern struct oidfed_federation_leaf oidfedFederationLeafCreateSimple(char* entityID, struct oidfed_versatile_signer signer, int* errc);
extern void oidfedFederationLeafDestroy(struct oidfed_federation_leaf* leaf);
extern struct oidfed_request_producer oidfedFederationLeafGetRequestObjectProducer(struct oidfed_federation_leaf leaf);
extern struct oidfed_map oidfCreateMap(void);
extern _Bool oidfMapHasKey(struct oidfed_map m, char* key);
extern void oidfMapSetString(struct oidfed_map m, char* key, char* value);
extern void oidfMapSetInt64(struct oidfed_map m, char* key, int64_t value);
extern struct oidfed_metadata oidfedMetadataCreate(void);
extern uintptr_t oidfedMetadataGetOPMetadata(struct oidfed_metadata m);
extern void oidfedMetadataSetOPMetadata(struct oidfed_metadata m, uintptr_t op);
extern uintptr_t oidfedMetadataGetRPMetadata(struct oidfed_metadata m);
extern void oidfedMetadataSetRPMetadata(struct oidfed_metadata m, uintptr_t rp);
extern struct oidfed_request_producer oidfedRequestProducerCreate(char* entityId, int64_t duration, struct oidfed_versatile_signer signer);
extern void oidfedRequestProducerDestroy(struct oidfed_request_producer* producer);
extern struct oidfed_signed_bytes oidfedRequestProducerProduceObject(struct oidfed_request_producer producer, struct oidfed_map requestValues, char** algorithms, size_t algorithmsCount, int* errc);
extern struct oidfed_signed_bytes oidfedRequestProducerClientAssertion(struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc);
extern void oidfedSignedBytesDestroy(struct oidfed_signed_bytes* sb);
extern char* oidfedSignedBytesGetData(struct oidfed_signed_bytes sb, size_t* count);
extern struct oidfed_signature_algorithm oidfedSignatureAlgorithmCreateEmpty(void);
extern void oidfedSignatureAlgorithmDestroy(struct oidfed_signature_algorithm* sa);
extern struct oidfed_signature_algorithm oidfedSignatureAlgorithmGet(char* name, _Bool* succ);
extern struct oidfed_signer oidfedSignerCreateFromPEM(char* pemBytes, size_t pemCount, int* errc);
extern void oidfedSignerDestroy(struct oidfed_signer* s);
extern struct oidfed_single_key_storage oidfedSingleKeyStorageCreate(struct oidfed_signer signer, struct oidfed_signature_algorithm alg);
extern void oidfedSingleKeyStorageDestroy(struct oidfed_single_key_storage* sks);
extern void oidfedTrustAnchorDestroy(struct oidfed_trust_anchor* ta);
extern struct oidfed_trust_anchor oidfedTrustAnchorCreate(char* id);
extern struct oidfed_trust_mark oidfedTrustMarkCreate(void);
extern void oidfedTrustMarkSetType(struct oidfed_trust_mark tm, char* typ);
extern char* oidfedTrustMarkGetType(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetIssuer(struct oidfed_trust_mark tm, char* issuer);
extern char* oidfedTrustMarkGetIssuer(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetSelfIssued(struct oidfed_trust_mark tm, _Bool selfIssued);
extern _Bool oidfedTrustMarkIsSelfIssued(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetJwt(struct oidfed_trust_mark tm, char* jwt);
extern char* oidfedTrustMarkGetJwt(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetRefresh(struct oidfed_trust_mark tm, _Bool refresh);
extern _Bool oidfedTrustMarkIsRefresh(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetMinLifetimeSeconds(struct oidfed_trust_mark tm, uint64_t minLifetime);
extern uint64_t oidfedTrustMarkGetMinLifetimeSeconds(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkSetRefreshGracePeriod(struct oidfed_trust_mark tm, uint64_t refreshGracePeriod);
extern uint64_t oidfedTrustMarkGetRefreshGracePeriod(struct oidfed_trust_mark tm);
extern void oidfedTrustMarkDestroy(struct oidfed_trust_mark* tm);
extern struct oidfed_trust_resolver oidfedTrustResolverCreate(char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount);
extern void oidfedTrustResolverDestroy(struct oidfed_trust_resolver* r);
extern struct oidfed_trust_chains oidfedTrustResolverResolveToValidChains(struct oidfed_trust_resolver r);
extern size_t oidfedTrustChainsCount(struct oidfed_trust_chains chains);
extern struct oidfed_trust_chain oidfedTrustChainsGet(struct oidfed_trust_chains chains, size_t index);
extern void oidfedTrustChainsDestroy(struct oidfed_trust_chains* chains);
extern void oidfedTrustChainDestroy(struct oidfed_trust_chain* chain);
extern struct oidfed_metadata oidfedTrustChainGetMetadata(struct oidfed_trust_chain chain, int* errc);
extern void oidfedMetadataDestroy(struct oidfed_metadata* m);
extern void oidfedUiInfoDestroy(struct oidfed_ui_info* ui);

#ifdef __cplusplus
}
#endif
